### ISSUE TITLE
remove rgeos from description file

### ISSUE THREAD

**Issue by Nithador** [ropensci/ReLTER#102]
Please, remove the rgeos package from the DESCRIPTION file, it was taken down from the CRAN and it seems it is not used anymore since it was deprecated in favour of sf and terra packages.

**Comment by oggioniale** [comment]
Thanks @Nithador for this issue.
I removed the rgeos package from the DESCRIPTION file
https://github.com/ropensci/ReLTER/commit/85ee714bce5895d97a338d8897d20ea2dbca531f
Let me know if is fine now

**Comment by Nithador** [comment]
Thanks for fast response, it can be installed again!
