### ISSUE TITLE
Manage DEIMS api versions

### ISSUE THREAD

**Issue by ptagliolato** [ropensci/ReLTER#59]
New API are coming. We must be able to adapt our logics to changes.
We can test on pre-production site with different url.
Proposal (partially done): 
- create global but adjustable package setting with base deims url (configurable in one's system variable) - done
- use package onLoad function to possibly change the base url variable reading from system. - done
- use a function to read from baseurl/api the deims version - done
- set a global (changeable) package setting to the read version (it's a string). - TODO
- put JQ queries in a variable (list) containing slots for API versions (e.g. jq_queries$'1.0' will be a list).
- adapt each function that contains a jq query to the new pattern: move the jq code into the JQ_queries variable. - STARTED for api version "1.0"
- add jq queries for version "1.1" and test the package against the pre-prod new version of deims - TODO

**Comment by oggioniale** [comment]
the commit 5ff2b3d951fed8d741b6291618d5d9f92c1b56d8 solve this issue
